---

kdc_port: 88
kdc_hostname: "{{ groups['kdc_server'][0] }}"
admin_hostname: "{{ groups['kdc_server'][0] }}"
dns_lookup_realm: "false"
dns_lookup_kdc: "false"
ticket_lifetime: "24h"
renew_lifetime: "7d"
forwardable: "true"
